add some SEO
maling-it/tools pull request #1
Opened 2024-01-30 14:23 UTC by Crownss

2024-01-30 14:33 UTC, Zxce3 approved these changes
Looks Good

2024-01-30 14:42 UTC, Zxce3 requested changes
I believe we shouldn't remove the yarn.lock file from the repository because doing so may cause issues with GitHub Actions. Please refer to https://github.com/maling-it/tools/actions/runs/7712790144 for more details.

2024-01-30 14:44 UTC, Zxce3 commented on src/components/CoreSwitcher.svelte
whats the point?

2024-01-30 14:44 UTC, Zxce3 commented on src/app.html
Looks good tho

2024-01-31 09:38 UTC, Crownss commented on src/components/CoreSwitcher.svelte
auto format perhaps

2024-01-31 09:39 UTC, Crownss commented
> I believe we shouldn't remove the yarn.lock file from the repository because doing so may cause issues with GitHub Actions. Please refer to https://github.com/maling-it/tools/actions/runs/7712790144 for more details.

i see thank you for your advice

2024-01-31 09:44 UTC, Crownss reviewed
remove yarn.lock from .gitignore

2024-01-31 10:02 UTC, merged